use std::collections::HashSet;
use std::fs;
use regex::Regex;

pub fn get_recent_failures() -> HashSet<String> {
    let mut failed_modules = HashSet::new();

    // Priority 1: FAILURE_REPORT.md (Generated by System)
    if let Ok(content) = fs::read_to_string("../../FAILURE_REPORT.md") {
        extract_failures(&content, &mut failed_modules);
    }

    // Priority 2: test_results.txt (Standard Output)
    if let Ok(content) = fs::read_to_string("../../test_results.txt") {
        extract_failures(&content, &mut failed_modules);
    }

    // Priority 3: app_test_fail.txt (Custom Hook)
    if let Ok(content) = fs::read_to_string("../../app_test_fail.txt") {
        extract_failures(&content, &mut failed_modules);
    }

    failed_modules
}

fn extract_failures(content: &str, set: &mut HashSet<String>) {
    // Look for ReScript/Rust file extensions in error logs
    let file_regex = Regex::new(r"([a-zA-Z0-9_\-\/]+\.(res|rs|js))").unwrap();

    // Look for ReScript module names in error logs (e.g., "Module.SubModule")
    // Avoid common words by ensuring it starts with Uppercase
    let module_regex = Regex::new(r"\b([A-Z][a-zA-Z0-9_]+)\b").unwrap();

    for line in content.lines() {
        if line.to_lowercase().contains("fail") || line.to_lowercase().contains("error") {
            for cap in file_regex.captures_iter(line) {
                if let Some(m) = cap.get(1) {
                    let path = m.as_str().to_string();
                    if !path.contains("node_modules") {
                        set.insert(path);
                    }
                }
            }

            for cap in module_regex.captures_iter(line) {
                if let Some(m) = cap.get(1) {
                    let module = m.as_str();
                    // Basic filtering of common words that look like modules
                    if module != "Error" && module != "Fail" && module != "Test" && module != "React" {
                         set.insert(module.to_string());
                    }
                }
            }
        }
    }
}
